
/**
 * KeenIoLib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ) on 02/05/2017
 */
var BaseModel = require("./BaseModel");
/**
 * Creates an instance of AvaliableChildProjectResourceResponse
 *
 * @constructor
 */
AvaliableChildProjectResourceResponse = function (obj) {
    if(!obj) {
        this.projectsResourceUrl = null;     
        //Append to variable dictionary
        this._variableDict['projectsResourceUrl'] = 'projects_resource_url';
    } else {
        this.projectsResourceUrl = (obj.projects_resource_url !== undefined && obj.projects_resource_url !== null)? obj.projects_resource_url : null;
        //Append to variable dictionary
        this._variableDict['projectsResourceUrl'] = 'projects_resource_url';
    }
};

AvaliableChildProjectResourceResponse.prototype = new BaseModel();
AvaliableChildProjectResourceResponse.prototype.constructor = AvaliableChildProjectResourceResponse;

/**
 * TODO: Write general description for this method
 *
 * @return {string}
 */
AvaliableChildProjectResourceResponse.prototype.getProjectsResourceUrl = function() {
    return this.projectsResourceUrl;
};

/**
 * Setter for ProjectsResourceUrl
 * 
 * @param {string} value 
 */
AvaliableChildProjectResourceResponse.prototype.setProjectsResourceUrl = function(value) {
    this.projectsResourceUrl = value;
};


module.exports = AvaliableChildProjectResourceResponse;
