
/**
 * KeenIoLib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ) on 02/05/2017
 */
var BaseModel = require("./BaseModel");
/**
 * Creates an instance of CountResponse
 *
 * @constructor
 */
CountResponse = function (obj) {
    if(!obj) {
        this.result = null;     
    } else {
        this.result = (obj.result !== undefined && obj.result !== null)? obj.result : null;
    }
};

CountResponse.prototype = new BaseModel();
CountResponse.prototype.constructor = CountResponse;

/**
 * TODO: Write general description for this method
 *
 * @return {int}
 */
CountResponse.prototype.getResult = function() {
    return this.result;
};

/**
 * Setter for Result
 * 
 * @param {int} value 
 */
CountResponse.prototype.setResult = function(value) {
    this.result = value;
};


module.exports = CountResponse;
