
/**
 * KeenIoLib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ) on 02/05/2017
 */
var BaseModel = require("./BaseModel");
/**
 * Creates an instance of CreatedResponse
 *
 * @constructor
 */
CreatedResponse = function (obj) {
    if(!obj) {
        this.created = null;     
    } else {
        this.created = (obj.created !== undefined && obj.created !== null)? obj.created : null;
    }
};

CreatedResponse.prototype = new BaseModel();
CreatedResponse.prototype.constructor = CreatedResponse;

/**
 * TODO: Write general description for this method
 *
 * @return {bool}
 */
CreatedResponse.prototype.getCreated = function() {
    return this.created;
};

/**
 * Setter for Created
 * 
 * @param {bool} value 
 */
CreatedResponse.prototype.setCreated = function(value) {
    this.created = value;
};


module.exports = CreatedResponse;
