
/**
 * KeenIoLib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ) on 02/05/2017
 */
var BaseModel = require("./BaseModel");
/**
 * Creates an instance of GetAPIVersionResponse
 *
 * @constructor
 */
GetAPIVersionResponse = function (obj) {
    if(!obj) {
        this.isPublic = null;     
        this.url = null;     
        this.version = null;     
        //Append to variable dictionary
        this._variableDict['isPublic'] = 'is_public';
    } else {
        this.isPublic = (obj.is_public !== undefined && obj.is_public !== null)? obj.is_public : null;
        this.url = (obj.url !== undefined && obj.url !== null)? obj.url : null;
        this.version = (obj.version !== undefined && obj.version !== null)? obj.version : null;
        //Append to variable dictionary
        this._variableDict['isPublic'] = 'is_public';
    }
};

GetAPIVersionResponse.prototype = new BaseModel();
GetAPIVersionResponse.prototype.constructor = GetAPIVersionResponse;

/**
 * TODO: Write general description for this method
 *
 * @return {bool}
 */
GetAPIVersionResponse.prototype.getIsPublic = function() {
    return this.isPublic;
};

/**
 * Setter for IsPublic
 * 
 * @param {bool} value 
 */
GetAPIVersionResponse.prototype.setIsPublic = function(value) {
    this.isPublic = value;
};

/**
 * TODO: Write general description for this method
 *
 * @return {string}
 */
GetAPIVersionResponse.prototype.getUrl = function() {
    return this.url;
};

/**
 * Setter for Url
 * 
 * @param {string} value 
 */
GetAPIVersionResponse.prototype.setUrl = function(value) {
    this.url = value;
};

/**
 * TODO: Write general description for this method
 *
 * @return {string}
 */
GetAPIVersionResponse.prototype.getVersion = function() {
    return this.version;
};

/**
 * Setter for Version
 * 
 * @param {string} value 
 */
GetAPIVersionResponse.prototype.setVersion = function(value) {
    this.version = value;
};


module.exports = GetAPIVersionResponse;
