
/**
 * KeenIoLib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ) on 02/05/2017
 */
var BaseModel = require("./BaseModel");
/**
 * Creates an instance of GetFunnelResourceResponse
 *
 * @constructor
 */
GetFunnelResourceResponse = function (obj) {
    if(!obj) {
        this.result = null;     
        this.steps = null;     
    } else {
        this.result = (obj.result !== undefined && obj.result !== null)? obj.result : null;
        this.steps = (obj.steps !== undefined && obj.steps !== null)? obj.steps.map(function(model){
            return new Steps(model);
        }) : null;
    }
};

GetFunnelResourceResponse.prototype = new BaseModel();
GetFunnelResourceResponse.prototype.constructor = GetFunnelResourceResponse;

/**
 * TODO: Write general description for this method
 *
 * @return {array}
 */
GetFunnelResourceResponse.prototype.getResult = function() {
    return this.result;
};

/**
 * Setter for Result
 * 
 * @param {array} value 
 */
GetFunnelResourceResponse.prototype.setResult = function(value) {
    this.result = value;
};

/**
 * TODO: Write general description for this method
 *
 * @return {array}
 */
GetFunnelResourceResponse.prototype.getSteps = function() {
    return this.steps;
};

/**
 * Setter for Steps
 * 
 * @param {array} value 
 */
GetFunnelResourceResponse.prototype.setSteps = function(value) {
    this.steps = value;
};


module.exports = GetFunnelResourceResponse;
