
/**
 * KeenIoLib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ) on 02/05/2017
 */
var BaseModel = require("./BaseModel");
/**
 * Creates an instance of GetProjectAccessibleResponse
 *
 * @constructor
 */
GetProjectAccessibleResponse = function (obj) {
    if(!obj) {
        this.partnersUrl = null;     
        this.name = null;     
        this.url = null;     
        this.savedQueries = null;     
        this.eventsUrl = null;     
        this.id = null;     
        this.organizationId = null;     
        this.queriesUrl = null;     
        this.apiKey = null;     
        this.events = null;     
        this.savedQueriesUrl = null;     
        //Append to variable dictionary
        this._variableDict['partnersUrl'] = 'partners_url';
        this._variableDict['savedQueries'] = 'saved_queries';
        this._variableDict['eventsUrl'] = 'events_url';
        this._variableDict['organizationId'] = 'organization_id';
        this._variableDict['queriesUrl'] = 'queries_url';
        this._variableDict['apiKey'] = 'api_key';
        this._variableDict['savedQueriesUrl'] = 'saved_queries_url';
    } else {
        this.partnersUrl = (obj.partners_url !== undefined && obj.partners_url !== null)? obj.partners_url : null;
        this.name = (obj.name !== undefined && obj.name !== null)? obj.name : null;
        this.url = (obj.url !== undefined && obj.url !== null)? obj.url : null;
        this.savedQueries = (obj.saved_queries !== undefined && obj.saved_queries !== null)? obj.saved_queries : null;
        this.eventsUrl = (obj.events_url !== undefined && obj.events_url !== null)? obj.events_url : null;
        this.id = (obj.id !== undefined && obj.id !== null)? obj.id : null;
        this.organizationId = (obj.organization_id !== undefined && obj.organization_id !== null)? obj.organization_id : null;
        this.queriesUrl = (obj.queries_url !== undefined && obj.queries_url !== null)? obj.queries_url : null;
        this.apiKey = (obj.api_key !== undefined && obj.api_key !== null)? obj.api_key : null;
        this.events = (obj.events !== undefined && obj.events !== null)? obj.events : null;
        this.savedQueriesUrl = (obj.saved_queries_url !== undefined && obj.saved_queries_url !== null)? obj.saved_queries_url : null;
        //Append to variable dictionary
        this._variableDict['partnersUrl'] = 'partners_url';
        this._variableDict['savedQueries'] = 'saved_queries';
        this._variableDict['eventsUrl'] = 'events_url';
        this._variableDict['organizationId'] = 'organization_id';
        this._variableDict['queriesUrl'] = 'queries_url';
        this._variableDict['apiKey'] = 'api_key';
        this._variableDict['savedQueriesUrl'] = 'saved_queries_url';
    }
};

GetProjectAccessibleResponse.prototype = new BaseModel();
GetProjectAccessibleResponse.prototype.constructor = GetProjectAccessibleResponse;

/**
 * TODO: Write general description for this method
 *
 * @return {string}
 */
GetProjectAccessibleResponse.prototype.getPartnersUrl = function() {
    return this.partnersUrl;
};

/**
 * Setter for PartnersUrl
 * 
 * @param {string} value 
 */
GetProjectAccessibleResponse.prototype.setPartnersUrl = function(value) {
    this.partnersUrl = value;
};

/**
 * TODO: Write general description for this method
 *
 * @return {string}
 */
GetProjectAccessibleResponse.prototype.getName = function() {
    return this.name;
};

/**
 * Setter for Name
 * 
 * @param {string} value 
 */
GetProjectAccessibleResponse.prototype.setName = function(value) {
    this.name = value;
};

/**
 * TODO: Write general description for this method
 *
 * @return {string}
 */
GetProjectAccessibleResponse.prototype.getUrl = function() {
    return this.url;
};

/**
 * Setter for Url
 * 
 * @param {string} value 
 */
GetProjectAccessibleResponse.prototype.setUrl = function(value) {
    this.url = value;
};

/**
 * TODO: Write general description for this method
 *
 * @return {array}
 */
GetProjectAccessibleResponse.prototype.getSavedQueries = function() {
    return this.savedQueries;
};

/**
 * Setter for SavedQueries
 * 
 * @param {array} value 
 */
GetProjectAccessibleResponse.prototype.setSavedQueries = function(value) {
    this.savedQueries = value;
};

/**
 * TODO: Write general description for this method
 *
 * @return {string}
 */
GetProjectAccessibleResponse.prototype.getEventsUrl = function() {
    return this.eventsUrl;
};

/**
 * Setter for EventsUrl
 * 
 * @param {string} value 
 */
GetProjectAccessibleResponse.prototype.setEventsUrl = function(value) {
    this.eventsUrl = value;
};

/**
 * TODO: Write general description for this method
 *
 * @return {string}
 */
GetProjectAccessibleResponse.prototype.getId = function() {
    return this.id;
};

/**
 * Setter for Id
 * 
 * @param {string} value 
 */
GetProjectAccessibleResponse.prototype.setId = function(value) {
    this.id = value;
};

/**
 * TODO: Write general description for this method
 *
 * @return {string}
 */
GetProjectAccessibleResponse.prototype.getOrganizationId = function() {
    return this.organizationId;
};

/**
 * Setter for OrganizationId
 * 
 * @param {string} value 
 */
GetProjectAccessibleResponse.prototype.setOrganizationId = function(value) {
    this.organizationId = value;
};

/**
 * TODO: Write general description for this method
 *
 * @return {string}
 */
GetProjectAccessibleResponse.prototype.getQueriesUrl = function() {
    return this.queriesUrl;
};

/**
 * Setter for QueriesUrl
 * 
 * @param {string} value 
 */
GetProjectAccessibleResponse.prototype.setQueriesUrl = function(value) {
    this.queriesUrl = value;
};

/**
 * TODO: Write general description for this method
 *
 * @return {string}
 */
GetProjectAccessibleResponse.prototype.getApiKey = function() {
    return this.apiKey;
};

/**
 * Setter for ApiKey
 * 
 * @param {string} value 
 */
GetProjectAccessibleResponse.prototype.setApiKey = function(value) {
    this.apiKey = value;
};

/**
 * TODO: Write general description for this method
 *
 * @return {array}
 */
GetProjectAccessibleResponse.prototype.getEvents = function() {
    return this.events;
};

/**
 * Setter for Events
 * 
 * @param {array} value 
 */
GetProjectAccessibleResponse.prototype.setEvents = function(value) {
    this.events = value;
};

/**
 * TODO: Write general description for this method
 *
 * @return {string}
 */
GetProjectAccessibleResponse.prototype.getSavedQueriesUrl = function() {
    return this.savedQueriesUrl;
};

/**
 * Setter for SavedQueriesUrl
 * 
 * @param {string} value 
 */
GetProjectAccessibleResponse.prototype.setSavedQueriesUrl = function(value) {
    this.savedQueriesUrl = value;
};


module.exports = GetProjectAccessibleResponse;
