
/**
 * KeenIoLib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ) on 02/05/2017
 */
var BaseModel = require("./BaseModel");
/**
 * Creates an instance of GetPropertyResourceResponse
 *
 * @constructor
 */
GetPropertyResourceResponse = function (obj) {
    if(!obj) {
        this.propertyName = null;     
        this.url = null;     
        this.type = null;     
        //Append to variable dictionary
        this._variableDict['propertyName'] = 'property_name';
    } else {
        this.propertyName = (obj.property_name !== undefined && obj.property_name !== null)? obj.property_name : null;
        this.url = (obj.url !== undefined && obj.url !== null)? obj.url : null;
        this.type = (obj.type !== undefined && obj.type !== null)? obj.type : null;
        //Append to variable dictionary
        this._variableDict['propertyName'] = 'property_name';
    }
};

GetPropertyResourceResponse.prototype = new BaseModel();
GetPropertyResourceResponse.prototype.constructor = GetPropertyResourceResponse;

/**
 * TODO: Write general description for this method
 *
 * @return {string}
 */
GetPropertyResourceResponse.prototype.getPropertyName = function() {
    return this.propertyName;
};

/**
 * Setter for PropertyName
 * 
 * @param {string} value 
 */
GetPropertyResourceResponse.prototype.setPropertyName = function(value) {
    this.propertyName = value;
};

/**
 * TODO: Write general description for this method
 *
 * @return {string}
 */
GetPropertyResourceResponse.prototype.getUrl = function() {
    return this.url;
};

/**
 * Setter for Url
 * 
 * @param {string} value 
 */
GetPropertyResourceResponse.prototype.setUrl = function(value) {
    this.url = value;
};

/**
 * TODO: Write general description for this method
 *
 * @return {string}
 */
GetPropertyResourceResponse.prototype.getType = function() {
    return this.type;
};

/**
 * Setter for Type
 * 
 * @param {string} value 
 */
GetPropertyResourceResponse.prototype.setType = function(value) {
    this.type = value;
};


module.exports = GetPropertyResourceResponse;
