
/**
 * KeenIoLib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ) on 02/05/2017
 */
var BaseModel = require("./BaseModel");
/**
 * Creates an instance of SavedQueriesListResourceResponse
 *
 * @constructor
 */
SavedQueriesListResourceResponse = function (obj) {
    if(!obj) {
        this.analysisType = null;     
        this.createdDate = null;     
        this.eventCollection = null;     
        this.filters = null;     
        this.queryName = null;     
        this.queryType = null;     
        this.interval = null;     
        this.lastModifiedDate = null;     
        this.timeframe = null;     
        this.urls = null;     
        //Append to variable dictionary
        this._variableDict['analysisType'] = 'analysis_type';
        this._variableDict['createdDate'] = 'created_date';
        this._variableDict['eventCollection'] = 'event_collection';
        this._variableDict['queryName'] = 'query_name';
        this._variableDict['queryType'] = 'query_type';
        this._variableDict['lastModifiedDate'] = 'last_modified_date';
    } else {
        this.analysisType = (obj.analysis_type !== undefined && obj.analysis_type !== null)? obj.analysis_type : null;
        this.createdDate = (obj.created_date !== undefined && obj.created_date !== null)? new Date(obj.created_date) : null;
        this.eventCollection = (obj.event_collection !== undefined && obj.event_collection !== null)? obj.event_collection : null;
        this.filters = (obj.filters !== undefined && obj.filters !== null)? obj.filters : null;
        this.queryName = (obj.query_name !== undefined && obj.query_name !== null)? obj.query_name : null;
        this.queryType = (obj.query_type !== undefined && obj.query_type !== null)? obj.query_type : null;
        this.interval = (obj.interval !== undefined && obj.interval !== null)? obj.interval : null;
        this.lastModifiedDate = (obj.last_modified_date !== undefined && obj.last_modified_date !== null)? new Date(obj.last_modified_date) : null;
        this.timeframe = (obj.timeframe !== undefined && obj.timeframe !== null)? new Date(obj.timeframe) : null;
        this.urls = (obj.urls !== undefined && obj.urls !== null)? new Urls(obj.urls) : null;
        //Append to variable dictionary
        this._variableDict['analysisType'] = 'analysis_type';
        this._variableDict['createdDate'] = 'created_date';
        this._variableDict['eventCollection'] = 'event_collection';
        this._variableDict['queryName'] = 'query_name';
        this._variableDict['queryType'] = 'query_type';
        this._variableDict['lastModifiedDate'] = 'last_modified_date';
    }
};

SavedQueriesListResourceResponse.prototype = new BaseModel();
SavedQueriesListResourceResponse.prototype.constructor = SavedQueriesListResourceResponse;

/**
 * TODO: Write general description for this method
 *
 * @return {string}
 */
SavedQueriesListResourceResponse.prototype.getAnalysisType = function() {
    return this.analysisType;
};

/**
 * Setter for AnalysisType
 * 
 * @param {string} value 
 */
SavedQueriesListResourceResponse.prototype.setAnalysisType = function(value) {
    this.analysisType = value;
};

/**
 * TODO: Write general description for this method
 *
 * @return {dateTime}
 */
SavedQueriesListResourceResponse.prototype.getCreatedDate = function() {
    return this.createdDate;
};

/**
 * Setter for CreatedDate
 * 
 * @param {dateTime} value 
 */
SavedQueriesListResourceResponse.prototype.setCreatedDate = function(value) {
    this.createdDate = value;
};

/**
 * TODO: Write general description for this method
 *
 * @return {string}
 */
SavedQueriesListResourceResponse.prototype.getEventCollection = function() {
    return this.eventCollection;
};

/**
 * Setter for EventCollection
 * 
 * @param {string} value 
 */
SavedQueriesListResourceResponse.prototype.setEventCollection = function(value) {
    this.eventCollection = value;
};

/**
 * TODO: Write general description for this method
 *
 * @return {array}
 */
SavedQueriesListResourceResponse.prototype.getFilters = function() {
    return this.filters;
};

/**
 * Setter for Filters
 * 
 * @param {array} value 
 */
SavedQueriesListResourceResponse.prototype.setFilters = function(value) {
    this.filters = value;
};

/**
 * TODO: Write general description for this method
 *
 * @return {string}
 */
SavedQueriesListResourceResponse.prototype.getQueryName = function() {
    return this.queryName;
};

/**
 * Setter for QueryName
 * 
 * @param {string} value 
 */
SavedQueriesListResourceResponse.prototype.setQueryName = function(value) {
    this.queryName = value;
};

/**
 * TODO: Write general description for this method
 *
 * @return {string}
 */
SavedQueriesListResourceResponse.prototype.getQueryType = function() {
    return this.queryType;
};

/**
 * Setter for QueryType
 * 
 * @param {string} value 
 */
SavedQueriesListResourceResponse.prototype.setQueryType = function(value) {
    this.queryType = value;
};

/**
 * TODO: Write general description for this method
 *
 * @return {string}
 */
SavedQueriesListResourceResponse.prototype.getInterval = function() {
    return this.interval;
};

/**
 * Setter for Interval
 * 
 * @param {string} value 
 */
SavedQueriesListResourceResponse.prototype.setInterval = function(value) {
    this.interval = value;
};

/**
 * TODO: Write general description for this method
 *
 * @return {dateTime}
 */
SavedQueriesListResourceResponse.prototype.getLastModifiedDate = function() {
    return this.lastModifiedDate;
};

/**
 * Setter for LastModifiedDate
 * 
 * @param {dateTime} value 
 */
SavedQueriesListResourceResponse.prototype.setLastModifiedDate = function(value) {
    this.lastModifiedDate = value;
};

/**
 * TODO: Write general description for this method
 *
 * @return {dateTime}
 */
SavedQueriesListResourceResponse.prototype.getTimeframe = function() {
    return this.timeframe;
};

/**
 * Setter for Timeframe
 * 
 * @param {dateTime} value 
 */
SavedQueriesListResourceResponse.prototype.setTimeframe = function(value) {
    this.timeframe = value;
};

/**
 * TODO: Write general description for this method
 *
 * @return {Urls}
 */
SavedQueriesListResourceResponse.prototype.getUrls = function() {
    return this.urls;
};

/**
 * Setter for Urls
 * 
 * @param {Urls} value 
 */
SavedQueriesListResourceResponse.prototype.setUrls = function(value) {
    this.urls = value;
};


module.exports = SavedQueriesListResourceResponse;
