
/**
 * KeenIoLib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ) on 02/05/2017
 */
var BaseModel = require("./BaseModel");
/**
 * Creates an instance of SelectUniqueResourceResponse
 *
 * @constructor
 */
SelectUniqueResourceResponse = function (obj) {
    if(!obj) {
        this.result = null;     
    } else {
        this.result = (obj.result !== undefined && obj.result !== null)? obj.result : null;
    }
};

SelectUniqueResourceResponse.prototype = new BaseModel();
SelectUniqueResourceResponse.prototype.constructor = SelectUniqueResourceResponse;

/**
 * TODO: Write general description for this method
 *
 * @return {array}
 */
SelectUniqueResourceResponse.prototype.getResult = function() {
    return this.result;
};

/**
 * Setter for Result
 * 
 * @param {array} value 
 */
SelectUniqueResourceResponse.prototype.setResult = function(value) {
    this.result = value;
};


module.exports = SelectUniqueResourceResponse;
