
/**
 * KeenIoLib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ) on 02/05/2017
 */
var BaseModel = require("./BaseModel");
/**
 * Creates an instance of Urls
 *
 * @constructor
 */
Urls = function (obj) {
    if(!obj) {
        this.savedQueryResultsUrl = null;     
        this.savedQueryUrl = null;     
        //Append to variable dictionary
        this._variableDict['savedQueryResultsUrl'] = 'saved_query_results_url';
        this._variableDict['savedQueryUrl'] = 'saved_query_url';
    } else {
        this.savedQueryResultsUrl = (obj.saved_query_results_url !== undefined && obj.saved_query_results_url !== null)? obj.saved_query_results_url : null;
        this.savedQueryUrl = (obj.saved_query_url !== undefined && obj.saved_query_url !== null)? obj.saved_query_url : null;
        //Append to variable dictionary
        this._variableDict['savedQueryResultsUrl'] = 'saved_query_results_url';
        this._variableDict['savedQueryUrl'] = 'saved_query_url';
    }
};

Urls.prototype = new BaseModel();
Urls.prototype.constructor = Urls;

/**
 * TODO: Write general description for this method
 *
 * @return {string}
 */
Urls.prototype.getSavedQueryResultsUrl = function() {
    return this.savedQueryResultsUrl;
};

/**
 * Setter for SavedQueryResultsUrl
 * 
 * @param {string} value 
 */
Urls.prototype.setSavedQueryResultsUrl = function(value) {
    this.savedQueryResultsUrl = value;
};

/**
 * TODO: Write general description for this method
 *
 * @return {string}
 */
Urls.prototype.getSavedQueryUrl = function() {
    return this.savedQueryUrl;
};

/**
 * Setter for SavedQueryUrl
 * 
 * @param {string} value 
 */
Urls.prototype.setSavedQueryUrl = function(value) {
    this.savedQueryUrl = value;
};


module.exports = Urls;
