/**
 * KeenIoLib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ) on 02/05/2017
 */

var Configuration = {
    //The base Uri for API calls
    BASEURI : "https://api.keen.io",

    //its value should just be your API Key
    authorization : ""

};

module.exports = Configuration;
